apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafbat-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kafbat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafbat-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafbat-ui
    spec:
      containers:
        - name: kafbat-ui
          image: ghcr.io/kafbat/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-kafka-bootstrap:9092
            - name: SERVER_PORT
              value: "8080"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: kafbat-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kafbat-ui
spec:
  selector:
    app.kubernetes.io/name: kafbat-ui
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafbat-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kafbat-ui
spec:
  to:
    kind: Service
    name: kafbat-ui
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None