apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: workshop-springboot-keda-autoscaling
  namespace: {{ .Release.Namespace }}
  labels:
    app: workshop-springboot-keda-autoscaling
spec:
  scaleTargetRef:
    name: workshop-springboot-keda-autoscaling
  minReplicaCount: 0
  maxReplicaCount: 3
  pollingInterval: 5
  cooldownPeriod: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-kafka-bootstrap.{{ .Release.Namespace }}.svc.cluster.local:9092
        consumerGroup: keda-autoscaling-consumer
        topic: keda-events
        lagThreshold: "5"
        activationLagThreshold: "1"
