apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: camel-binding
  namespace: {{ .Release.Namespace }}
spec:
  params:
    - name: git-url
      value: $(body.project.http_url)
    - name: git-revision
      value: main
    - name: namespace
      value: {{ .Release.Namespace }}

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: camel-template
  namespace: {{ .Release.Namespace }}
  labels:
    backstage.io/kubernetes-id: workshop-springboot-using_camel
spec:
  params:
    - name: git-url
    - name: git-revision
      default: refs/heads/main
    - name: namespace
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: springboot-build-deploy-camel-
        namespace: {{ .Release.Namespace }}
        labels:
          backstage.io/kubernetes-id: workshop-springboot-using_camel
      spec:
        pipelineRef:
          name: springboot-build-deploy
        serviceAccountName: pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image
            value: image-registry.openshift-image-registry.svc:5000/$(tt.params.namespace)/workshop-springboot-using_camel:latest
          - name: appName
            value: workshop-springboot-using_camel
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 2Gi

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: camel-listener
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: pipeline
  triggers:
    - name: gitlab-push
      interceptors:
        - ref:
            name: gitlab
          params:
            - name: eventTypes
              value:
                - Push Hook
      bindings:
        - ref: camel-binding
      template:
        ref: camel-template

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: camel-listener
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: el-camel-listener
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
